spring:
  datasource:
    url: jdbc:postgresql://localhost:32770/mustache
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sendgrid:
    api-key: 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


